### ISSUE TITLE
php 5.3 support

### ISSUE THREAD

**Issue by nephilem90** [markrogoyski/ipv4-subnet-calculator-php#10]
Hello,

in your composer you show support to PHP 5.3 but in this version it isn't possible to define arrays like this

$array = []

**Comment by markrogoyski** [comment]
Thank you for bringing this to my attention. You are right. Short array syntax was introduced in PHP 5.4, so that should be the minimum version supported. It should not be a problem to up the minimum supported version, as PHP 5.3 has officially been unsupported since 2014.

I will update this in the next release.

**Comment by markrogoyski** [comment]
[v3.0.0](https://github.com/markrogoyski/ipv4-subnet-calculator-php/releases/tag/v3.0.0) now indicates that PHP 5.5 is the lowest minimum supported version. Thanks.
